M48
; DRILL file {KiCad (6.0.10-0)} date Saturday, May 27, 2023 at 03:28:01 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-27T15:28:01-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X103.5Y-47.5
X103.5Y-96.5
X161.5Y-47.5
X161.5Y-96.5
T0
M30
